name: Publish Zig Build Image

on:
  push:
    paths:
      - 'zig/Dockerfile'
      - '.github/workflows/docker-publish.yml'
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      ZIG_VERSION: 0.14.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: zig/Dockerfile
          push: true
          build-args: |
            ZIG_VERSION=${{ env.ZIG_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}/zig-cpp:latest
            ghcr.io/${{ github.repository }}/zig-cpp:${{ env.ZIG_VERSION }}